### ISSUE TITLE
Create and connect to a CfA subaccount

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#61]
Right now the builder prompts the user to set up their CityVoice survey with a number from a free,trial Twilio account. The trial accounts give every survey respondent calling in a confusing "please upgrade your account" prompt. This will deter City staff users from pushing out their survey. 

To avoid the prompt message, Twilio has advised us to set up sub-accounts for users that give them access to CfA credits. This requires a few significant changes in the builder:
* Remove direction to set up a Twilio account
* Create subaccount for the city with request to the Twilio API
* Connect the phone number to the Heroku through automation _OR_ serve up a login to the Twilio subaccount for a user to do themselves

Related documentation for creating subaccountsI: https://www.twilio.com/docs/howto/subaccounts

**Comment by migurski** [comment]
I will work with Twilio’s accounts API today to see what volume of blood and tears are required to make this possible, and I’ll bug @daguar if/when needed.

**Comment by daguar** [comment]
:+1: It's a pretty straightforward API design.

You will probably want to ask people for information about who they are and then set the `friendly_name` attribute on the phone number to something like that, keeping a separate crosswalk to contact info.

**Comment by migurski** [comment]
Cool. My plan is to make this go using Python, so I don’t blow an afternoon struggling with Ruby. Once I’m confident I understand Twilio’s API for this feature, I’ll come scratch at your door.

**Comment by daguar** [comment]
:+1: Just because I'm familiar with it, here's a tiny skeleton with links to the docs that might be useful:

- Create new subaccount and set friendly name ( https://www.twilio.com/docs/api/rest/subaccounts )
- With that subaccount, find an available phone number ( https://www.twilio.com/docs/api/rest/available-phone-numbers )
- Purchase that available phone number which makes it an INCOMING phone number on the account ( https://www.twilio.com/docs/api/rest/incoming-phone-numbers )
- Set VoiceURL for the phone number (same as above, https://www.twilio.com/docs/api/rest/incoming-phone-numbers )

After writing this all out, another approach would be to simply allocate to the city a phone number and deal with transferring it later if wanted. Not sure if it's easier to transfer a phone # or a subaccount but creating a subaccount-per-city may be unnecessary (though I would use a CfA subaccount to silo this.)

**Comment by daguar** [comment]
And — as writing stuff out tends to do — I've realized I'm not sure you can create a subaccount _under another_ subaccount, so doing single number purchase per builder-app may be the wiser course anyway.

**Comment by migurski** [comment]
"Subaccounts cannot contain subaccounts," says the API response when I try.

**Comment by daguar** [comment]
![200_s](https://cloud.githubusercontent.com/assets/994938/7400498/3746a464-ee72-11e4-8e6f-782f0edd91ec.gif)

**Comment by migurski** [comment]
![Feints within feints](http://www.soundonsight.org/wp-content/uploads/2012/03/dunefight.jpg)

**Comment by migurski** [comment]
Asking for [local phone numbers using `AvailablePhoneNumbers`](https://www.twilio.com/docs/api/rest/available-phone-numbers):

    curl -G https://api.twilio.com/2010-04-01/Accounts/{Account SID}/AvailablePhoneNumbers/US/Local.json \
         -u {Account SID}:{Auth Token} \
         -d 'ExcludeLocalAddressRequired=true' \
         -d 'NearLatLong={Latitude},{Longitude}' \
         -d 'Distance={Miles}'

Partial response:

    {
      "available_phone_numbers": [
        {
          "address_requirements": "none",
          "capabilities": {
            "MMS": true,
            "SMS": true,
            "voice": true
          },
          "friendly_name": "(510) 860-4781",
          "iso_country": "US",
          "lata": "722",
          "latitude": "37.935800",
          "longitude": "-122.347800",
          "phone_number": "+15108604781",
          "postal_code": "94805",
          "rate_center": "RICHMOND",
          "region": "CA"
        },
        ...

**Comment by migurski** [comment]
Reserving a [local number using `IncomingPhoneNumbers`](https://www.twilio.com/docs/api/rest/incoming-phone-numbers):

    curl -X POST https://api.twilio.com/2010-04-01/Accounts/{Account SID}/IncomingPhoneNumbers.json \
         -u {Account SID}:{Auth Token} \
         -d 'FriendlyName={Friendly Name}' \
         -d 'PhoneNumber={Phone Number}'

Sample response:

    {
      "account_sid": "xxxxxxx",
      "address_requirements": "none",
      "api_version": "2010-04-01",
      "capabilities": {"mms": true, "sms": true, "voice": true},
      "date_created": "Wed, 29 Apr 2015 21:04:16 +0000",
      "date_updated": "Wed, 29 Apr 2015 21:04:16 +0000",
      "friendly_name": "Womp Womp Line",
      "phone_number": "ddddddd",
      "sid": "nnnnnnn",
      "sms_application_sid": "",
      "sms_fallback_method": "POST",
      "sms_fallback_url": "",
      "sms_method": "POST",
      "sms_url": "",
      "status_callback": "",
      "status_callback_method": "POST",
      "trunk_sid": null,
      "uri": "/2010-04-01/Accounts/xxxxxxx/IncomingPhoneNumbers/nnnnnnn.json",
      "voice_application_sid": "",
      "voice_caller_id_lookup": false,
      "voice_fallback_method": "POST",
      "voice_fallback_url": null,
      "voice_method": "POST",
      "voice_url": null
    }

**Comment by migurski** [comment]
Following up to [add a voice URL using `IncomingPhoneNumbers`](https://www.twilio.com/docs/api/rest/incoming-phone-numbers):

    curl -X POST https://api.twilio.com/2010-04-01/Accounts/{Account SID}/IncomingPhoneNumbers.json \
         -u {Account SID}:{Auth Token} \
         -d 'VoiceUrl={Voice URL}'

Sample response:

    {
      "account_sid": "xxxxxxx",
      "address_requirements": "none",
      "api_version": "2010-04-01",
      "capabilities": {"mms": true, "sms": true, "voice": true},
      "date_created": "Wed, 29 Apr 2015 21:04:16 +0000",
      "date_updated": "Wed, 29 Apr 2015 21:04:16 +0000",
      "friendly_name": "Womp Womp Line",
      "phone_number": "ddddddd",
      "sid": "nnnnnnn",
      "sms_application_sid": "",
      "sms_fallback_method": "POST",
      "sms_fallback_url": "",
      "sms_method": "POST",
      "sms_url": "",
      "status_callback": "",
      "status_callback_method": "POST",
      "trunk_sid": null,
      "uri": "/2010-04-01/Accounts/xxxxxxx/IncomingPhoneNumbers/nnnnnnn.json",
      "voice_application_sid": "",
      "voice_caller_id_lookup": false,
      "voice_fallback_method": "POST",
      "voice_fallback_url": null,
      "voice_method": "POST",
      "voice_url": "http://uuuuuuuu"
    }

**Comment by migurski** [comment]
Getting Heroku user [email address using Account Info](https://devcenter.heroku.com/articles/platform-api-reference#account-info):

    curl https://api.heroku.com/account \
         -H 'Authorization: Bearer {OAuth Bearer Token}' \
         -H 'Accept: application/vnd.heroku+json; version=3'

Sample response:

    {
      "allow_tracking":true,
      "beta":false,
      "email":"eeeeeee@ddddddd",
      "id":"nnnnnnn",
      "last_login":"2015-04-29T17:40:43Z",
      "name":null,
      "two_factor_authentication":false,
      "verified":false,
      "created_at":"2013-05-10T22:39:41Z",
      "updated_at":"2015-04-29T22:24:31Z",
      "default_organization":null
    }
