### ISSUE TITLE
Direct troubleshooters to CityVoice@ instead of Dave

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#63]
Change all instances of dave@codeforamerica.org to cityvoice@codeforamerica.org

![screen shot 2015-04-29 at 4 49 40 pm](https://cloud.githubusercontent.com/assets/1261618/7403919/36772202-ee90-11e4-9e0a-d624a0f80af6.png)

**Comment by daguar** [comment]
Currently directs users to email you @jmadans at jack@ — okay to close?

**Comment by jmadans** [comment]
Done!
