### ISSUE TITLE
Make the location selection map bigger!

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#73]
The map currently has a letterbox shape which is hard for users to navigate, especially when zoomed in. Could we enlarge to be a square?

![location_map](https://cloud.githubusercontent.com/assets/1261618/8344134/dfde877c-1a91-11e5-92e0-894623020e3b.png)

**Comment by daguar** [comment]
That'd be a simple HTML/CSS change. No huge lift.

**Comment by jmadans** [comment]
Done!
