### ISSUE TITLE
Keeps asking for microphone access on every page

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#74]
Each page of the builder is asking for microphone permissions. Bug?

**Comment by daguar** [comment]
Chrome remembers your preference for a URL if it's using HTTPS (per https://support.google.com/chrome/answer/2693767?hl=en-GB ) We don't force HTTPS on this app, but I could help make that happen if we wanted to.

So @jmadans , try it out on an HTTPS URL and see if it asks you on every page:
- if it does, then there's no way around it (they're distinct URLs, and it's not remembering at the host level)
- if it DOESN'T, then this can be solved this by forcing HTTPS

**Comment by migurski** [comment]
FYI, we do have and support HTTPS at https://cityvoice-setup.codeforamerica.org.

**Comment by daguar** [comment]
If you want to force SSL, it's pretty easy using this gem: https://github.com/josh/rack-ssl 

Then, at the top of the web app's class body, put something like:

```ruby
use Rack::SSL if settings.environment == :production # might be a string, 'production', I forget off-hand
```

**Comment by migurski** [comment]
Closing this one, continuing in #82.
