### ISSUE TITLE
How important is toll-free?

### ISSUE THREAD

**Issue by jmadans** [codeforamerica/cityvoice-survey-builder#85]
The call-in surveys generated by the builder are not toll-free for the users. Does this significantly hamper accessibility, response rate, or put us on the wrong - and potentially illegal - side of ADA/equal access. 

This is a research task for @jmadans.

**Comment by daguar** [comment]
I can't imagine the normal call-in rate applying is illegal in any way; just probably good to note it.

**Comment by daguar** [comment]
(A bit more context: any number already presumes you have a phone, so...)
